// Generated by https://quicktype.io

export interface TokenResponse {
    success: boolean;
    expires_at: string;
    request_token: string;
    session_id?: string;
    status_code?: number;
    status_message?: string;
}
